<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="<?= $options["description"]; ?>">
    <title><?= $options["title"]; ?></title>
</head>
<body>
    <h3>Navbar</h3>
    <?= $v->section("content"); ?>
    <h3>Footer</h3>
</body>
</html>